// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.1
// source: proto/report.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilterDate     string                 `protobuf:"bytes,1,opt,name=filter_date,json=filterDate,proto3" json:"filter_date,omitempty"`
	FilterType     string                 `protobuf:"bytes,2,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	TimeSeriesJson []byte                 `protobuf:"bytes,3,opt,name=time_series_json,json=timeSeriesJson,proto3" json:"time_series_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_proto_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetFilterDate() string {
	if x != nil {
		return x.FilterDate
	}
	return ""
}

func (x *ReportRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *ReportRequest) GetTimeSeriesJson() []byte {
	if x != nil {
		return x.TimeSeriesJson
	}
	return nil
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfContent    []byte                 `protobuf:"bytes,1,opt,name=pdf_content,json=pdfContent,proto3" json:"pdf_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_proto_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_report_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResponse) GetPdfContent() []byte {
	if x != nil {
		return x.PdfContent
	}
	return nil
}

var File_proto_report_proto protoreflect.FileDescriptor

const file_proto_report_proto_rawDesc = "" +
	"\n" +
	"\x12proto/report.proto\x12\x06report\"{\n" +
	"\rReportRequest\x12\x1f\n" +
	"\vfilter_date\x18\x01 \x01(\tR\n" +
	"filterDate\x12\x1f\n" +
	"\vfilter_type\x18\x02 \x01(\tR\n" +
	"filterType\x12(\n" +
	"\x10time_series_json\x18\x03 \x01(\fR\x0etimeSeriesJson\"1\n" +
	"\x0eReportResponse\x12\x1f\n" +
	"\vpdf_content\x18\x01 \x01(\fR\n" +
	"pdfContent2M\n" +
	"\rReportService\x12<\n" +
	"\vGeneratePdf\x12\x15.report.ReportRequest\x1a\x16.report.ReportResponseB*Z(github.com/fs-assignment/service-b/protob\x06proto3"

var (
	file_proto_report_proto_rawDescOnce sync.Once
	file_proto_report_proto_rawDescData []byte
)

func file_proto_report_proto_rawDescGZIP() []byte {
	file_proto_report_proto_rawDescOnce.Do(func() {
		file_proto_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_report_proto_rawDesc), len(file_proto_report_proto_rawDesc)))
	})
	return file_proto_report_proto_rawDescData
}

var file_proto_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_report_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: report.ReportRequest
	(*ReportResponse)(nil), // 1: report.ReportResponse
}
var file_proto_report_proto_depIdxs = []int32{
	0, // 0: report.ReportService.GeneratePdf:input_type -> report.ReportRequest
	1, // 1: report.ReportService.GeneratePdf:output_type -> report.ReportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_report_proto_init() }
func file_proto_report_proto_init() {
	if File_proto_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_report_proto_rawDesc), len(file_proto_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_report_proto_goTypes,
		DependencyIndexes: file_proto_report_proto_depIdxs,
		MessageInfos:      file_proto_report_proto_msgTypes,
	}.Build()
	File_proto_report_proto = out.File
	file_proto_report_proto_goTypes = nil
	file_proto_report_proto_depIdxs = nil
}
